# Generated by Django 4.1.2 on 2022-10-12 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortName', models.CharField(max_length=255)),
                ('countryName', models.CharField(max_length=255)),
                ('phoneCode', models.IntegerField()),
            ],
            options={
                'db_table': 'all_countries',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='countryCodeId',
            field=models.ForeignKey(db_column='countryCodeId', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='countryCode_ref', to='auth_APIs.allcountries'),
            preserve_default=False,
        ),
    ]
