# Generated by Django 4.1.2 on 2022-10-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0002_allcountries_user_countrycodeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
