# Generated by Django 4.1.2 on 2022-10-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0003_remove_user_lat_remove_user_lng_remove_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='countryCode',
        ),
    ]
