# Generated by Django 4.1.2 on 2022-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0004_remove_user_countrycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authServiceProviderId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='authServiceProviderType',
            field=models.IntegerField(choices=[(1, 'google'), (2, 'facebook'), (3, 'apple')], null=True),
        ),
    ]
