# Generated by Django 4.1.2 on 2022-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0005_user_authserviceproviderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
