# Generated by Django 4.1.2 on 2022-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0006_user_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='city',
        ),
    ]
