# Generated by Django 4.1.2 on 2022-10-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0007_rename_location_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genderTypeId',
            field=models.ForeignKey(db_column='genderTypeId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genderType_ref', to='auth_APIs.gendertype'),
        ),
    ]
