# Generated by Django 4.1.2 on 2022-10-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0008_alter_user_gendertypeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deviceTypeId',
            field=models.ForeignKey(db_column='deviceTypeId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deviceType_ref', to='auth_APIs.devicetype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTypeId',
            field=models.ForeignKey(db_column='userTypeId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userType_ref', to='auth_APIs.usertype'),
        ),
    ]
