# Generated by Django 4.1.2 on 2022-11-01 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0010_alter_user_countrycodeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoerUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNavStatus', models.IntegerField(choices=[(1, 'personalInformation'), (2, 'workServices'), (3, 'identification'), (4, 'billingInfo'), (5, 'compInfo')], default=1)),
                ('idImageUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='doer_user_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doer_data',
            },
        ),
    ]
