# Generated by Django 4.1.2 on 2022-11-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0012_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_category',
        ),
    ]
