# Generated by Django 4.1.2 on 2022-11-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0013_alter_category_table_alter_subcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
