# Generated by Django 4.1.2 on 2022-11-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0016_alter_user_authserviceproviderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='iconUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
