# Generated by Django 4.1.2 on 2022-11-07 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0017_category_iconurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyType', models.IntegerField(choices=[(1, 'individual'), (2, 'company')], default=1)),
                ('companyName', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.AddField(
            model_name='doeruserdata',
            name='companyId',
            field=models.ForeignKey(db_column='companyId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_info_ref', to='auth_APIs.company'),
        ),
    ]
