# Generated by Django 4.1.2 on 2022-11-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0018_company_doeruserdata_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isApproved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
