# Generated by Django 4.1.2 on 2022-11-09 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0019_company_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='userId',
            field=models.ForeignKey(db_column='userId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comp_ref', to=settings.AUTH_USER_MODEL),
        ),
    ]
