# Generated by Django 4.1.2 on 2022-11-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0020_company_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='doer_gellery_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gellery',
            },
        ),
    ]
