# Generated by Django 4.1.2 on 2022-11-15 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0022_alter_gellery_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255)),
                ('productDescription', models.TextField(default=None, null=True)),
                ('productImageUrl', models.CharField(max_length=255)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='doer_product_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doer_products',
            },
        ),
    ]
