# Generated by Django 4.1.2 on 2022-12-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0025_user_lat_user_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
    ]
