# Generated by Django 4.1.2 on 2022-12-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0026_user_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.AddField(
            model_name='doeruserdata',
            name='about',
            field=models.TextField(default=None, null=True),
        ),
    ]
