# Generated by Django 4.1.2 on 2022-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0027_remove_user_about_doeruserdata_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doeruserdata',
            name='userNavStatus',
            field=models.IntegerField(choices=[(1, 'personalInformation'), (2, 'workServices'), (3, 'identification'), (4, 'billingInfo'), (5, 'compInfo'), (6, 'about')], default=1),
        ),
    ]
