# Generated by Django 4.1.2 on 2023-01-05 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0028_alter_doeruserdata_usernavstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethodId', models.CharField(max_length=255)),
                ('fingerprint', models.CharField(max_length=255)),
                ('cardStatus', models.IntegerField(choices=[(1, 'ordinary'), (2, 'default')], default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='customerCard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_cards',
            },
        ),
    ]
