# Generated by Django 4.1.2 on 2023-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0030_allcountries_flagiconurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCountries1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortName', models.CharField(max_length=255)),
                ('countryName', models.CharField(max_length=255)),
                ('phoneCode', models.IntegerField()),
                ('flagIconUrl', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'all_countries1',
            },
        ),
    ]
