# Generated by Django 4.1.2 on 2023-03-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0031_allcountries1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllCountries1',
        ),
        migrations.AlterModelTable(
            name='allcountries',
            table='all_countries1',
        ),
    ]
