# Generated by Django 4.1.2 on 2023-03-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0032_delete_allcountries1_alter_allcountries_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allcountries',
            table='all_countries',
        ),
    ]
