# Generated by Django 4.1.2 on 2023-03-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0033_alter_allcountries_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countryCodeId',
            field=models.ForeignKey(db_column='countryCodeId', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryCode_ref', to='auth_APIs.allcountries'),
        ),
    ]
