# Generated by Django 4.1.2 on 2023-07-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0034_alter_user_countrycodeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNo',
            field=models.CharField(max_length=255),
        ),
    ]
