# Generated by Django 4.1.2 on 2022-12-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStatus', models.IntegerField(choices=[(1, 'initiated'), (2, 'Running'), (3, 'Rejected'), (4, 'completed'), (5, 'failed'), (6, 'cancelled')], default=1)),
                ('jobPanelStatus', models.IntegerField(choices=[(1, 'intitiate'), (2, 'share_job'), (3, 'request_proposal'), (4, 'waiting'), (5, 'cust_proposal_action')], default=None, null=True)),
                ('jobDescription', models.TextField()),
                ('chatId', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doerId', models.ForeignKey(db_column='doerId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doer_panel_ref', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='user_panel_ref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.CharField(default=None, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doerId', models.ForeignKey(db_column='doerId', on_delete=django.db.models.deletion.CASCADE, related_name='doer_proposal_ref', to=settings.AUTH_USER_MODEL)),
                ('jobId', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='jobId_proposal_Id', to='chatPanel.job')),
            ],
            options={
                'db_table': 'job_proposals',
            },
        ),
        migrations.CreateModel(
            name='JobProposalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('offerId', models.ForeignKey(db_column='offerId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerId_proposal_ref', to=settings.AUTH_USER_MODEL)),
                ('productId', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='productId_proposal_ref', to=settings.AUTH_USER_MODEL)),
                ('proposalId', models.ForeignKey(db_column='proposalId', on_delete=django.db.models.deletion.CASCADE, related_name='proposal_Id', to='chatPanel.jobproposal')),
            ],
            options={
                'db_table': 'job_proposal_products',
            },
        ),
        migrations.CreateModel(
            name='JobAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignStatus', models.IntegerField(choices=[(1, 'initiated'), (2, 'Running'), (3, 'Rejected'), (4, 'completed'), (5, 'failed'), (6, 'cancelled')], default=1)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doerId', models.ForeignKey(db_column='doerId', on_delete=django.db.models.deletion.CASCADE, related_name='doer_assign_ref', to=settings.AUTH_USER_MODEL)),
                ('jobId', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='jobId_assign_Id', to='chatPanel.job')),
            ],
            options={
                'db_table': 'job_assign',
            },
        ),
    ]
