# Generated by Django 4.1.2 on 2022-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isJobShare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='searchKeyword',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobassign',
            name='assignStatus',
            field=models.IntegerField(choices=[(1, 'initiated'), (2, 'Accepted'), (3, 'Rejected'), (4, 'completed'), (5, 'failed'), (6, 'cancelled')], default=1),
        ),
    ]
