# Generated by Django 3.2 on 2022-12-28 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0028_alter_doeruserdata_usernavstatus'),
        ('chatPanel', '0002_job_isjobshare_job_searchkeyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='subCatId',
            field=models.ForeignKey(db_column='subCatId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subCat_panel_ref', to='auth_APIs.subcategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='chatId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='searchKeyword',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
