# Generated by Django 4.1.2 on 2022-12-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0003_auto_20221228_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobproposal',
            name='ammount',
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='discountAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='shortDescription',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobproposalproduct',
            name='discountedAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobproposalproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
