# Generated by Django 4.1.2 on 2022-12-30 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_APIs', '0028_alter_doeruserdata_usernavstatus'),
        ('chatPanel', '0004_remove_jobproposal_ammount_jobproposal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobproposalproduct',
            name='offerId',
            field=models.ForeignKey(db_column='offerId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerId_proposal_ref', to='auth_APIs.offer'),
        ),
        migrations.AlterField(
            model_name='jobproposalproduct',
            name='productId',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='productId_proposal_ref', to='auth_APIs.product'),
        ),
    ]
