# Generated by Django 4.1.2 on 2023-01-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0005_alter_jobproposalproduct_offerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproposal',
            name='status',
            field=models.IntegerField(choices=[(1, 'initiated'), (2, 'Accepted'), (3, 'Rejected'), (6, 'cancelled')], default=1),
        ),
    ]
