# Generated by Django 4.1.2 on 2023-01-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0006_jobproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobproposal',
            name='status',
            field=models.IntegerField(choices=[(1, 'initiated'), (2, 'Accepted'), (3, 'Rejected'), (4, 'cancelled')], default=1),
        ),
    ]
