# Generated by Django 4.1.2 on 2023-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0007_alter_jobproposal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobStatus',
            field=models.IntegerField(choices=[(1, 'initiated'), (2, 'Running'), (3, 'Accepted'), (4, 'completed'), (5, 'failed'), (6, 'cancelled')], default=1),
        ),
    ]
