# Generated by Django 4.1.2 on 2023-01-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0009_job_cancelotherreason_job_cancelreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobPanelStatus',
            field=models.IntegerField(choices=[(1, 'intitiate'), (2, 'share_job'), (3, 'request_proposal'), (4, 'waiting'), (5, 'cust_proposal_action'), (6, 'rating_review'), (7, 'complete')], default=None, null=True),
        ),
    ]
