# Generated by Django 4.1.2 on 2023-01-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0010_alter_job_jobpanelstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRatingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField(default=None, null=True)),
                ('jobId', models.ForeignKey(db_column='jobId', on_delete=django.db.models.deletion.CASCADE, related_name='jobId_rating_ref', to='chatPanel.job')),
            ],
            options={
                'db_table': 'rating_reviews',
            },
        ),
    ]
