# Generated by Django 4.1.2 on 2023-01-20 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0011_jobratingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobratingreview',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
