# Generated by Django 4.1.2 on 2023-01-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatPanel', '0012_jobratingreview_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobassign',
            name='assignStatus',
            field=models.IntegerField(choices=[(1, 'initiated'), (2, 'ProposalCreated'), (3, 'Accepted'), (4, 'rejected')], default=1),
        ),
    ]
