# Generated by Django 4.1.2 on 2023-01-24 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatPanel', '0013_alter_jobassign_assignstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobratingreview',
            name='doerId',
            field=models.ForeignKey(db_column='doerId', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doerId_rating_ref', to=settings.AUTH_USER_MODEL),
        ),
    ]
