# Generated by Django 4.1.2 on 2023-01-31 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Open'), (3, 'Closed')], default=1)),
                ('query', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('userId', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='userId_Query', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_queries',
            },
        ),
        migrations.CreateModel(
            name='QueryChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('isRead', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('receiverId', models.ForeignKey(db_column='receiverId', on_delete=django.db.models.deletion.CASCADE, related_name='receiverId_QueryChat', to=settings.AUTH_USER_MODEL)),
                ('senderId', models.ForeignKey(db_column='senderId', on_delete=django.db.models.deletion.CASCADE, related_name='senderId_QueryChat', to=settings.AUTH_USER_MODEL)),
                ('ticketId', models.ForeignKey(db_column='ticketId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticketId_QueryChat', to='support.queryticket')),
            ],
            options={
                'db_table': 'query_chats',
            },
        ),
    ]
