# Generated by Django 4.1.2 on 2023-01-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='queryticket',
            table='query_tickets',
        ),
    ]
