from django.urls import path
from userManagement import views

urlpatterns = [
    path('',views.adminLogin, name='admin-login'), 
    path('admin-dashboard/', views.adminDashboard, name="admin-dashboard"),
    path('logout',views.logoutAdmin, name="logout-admin"),
    path('customer-users/', views.CustomerUsers.as_view(), name='customer-users'),
    path('customer-view-detail/<int:userId>/', views.customerViewDetail, name='customer-details'),
    path('block-unblock/<int:userId>/', views.blockUnblock, name='block-unblock'),
    path('delete-user/', views.deleteUser, name='delete-user'),
    path('search-customer-user/', views.searchUserPetient, name='customer-user-search'),
    path('filter-active-block-customer/', views.filterByStatusActiveBlock, name='customer-act-block-filter'),
    path('admin-forget-password/', views.admin_forget_password,name = "admin-forget-password"),
    path('admin-change-password/<token>/', views.admin_change_password, name='set-new-admin-password'),
    path('doer-user-requests/', views.DoerUserRequest.as_view(), name='doer-usr-requests'),
    path('doer-view-details/<int:userId>/', views.viewDetail, name='doer-view-detail'),
    path('request-status-change/<int:status>/<int:userId>/', views.changeRequestStatus, name='change-status-user'),
    path('filter-by-status/', views.filterByStatus, name='filter-by-status'),
    path('search-doer/', views.searchUserRequest, name='doer-search'),
    path('approved-doers/', views.DoerApprovedUsers.as_view(), name='approved-users-doer'),
    path('filter-active-block/', views.filterByStatusApproved, name='active-block-filter'),
    path('search-approved-user/', views.searchUserApproved, name='search-approved-user'),
    path('admin-cat-list/', views.AdminCategoryRequestList.as_view(), name='admin-cat-list'),
    path('doer-cat-requests/', views.CategoryRequestList.as_view(), name='doer-cat-request-list'),
    path('reject-doer-category/<int:catId>/', views.rejectDoerCategoryRequest, name='reject-doer-category'),
    path('approved-doer-car-request/<int:catId>/', views.approveDoerCategoryRequest, name='approved-cat-request'),
    path('add-category/',views.addCategory, name='add-category'),
    path('view-details-admin/<int:catId>/', views.viewDetailsAdmin, name='view-admin-details'),
    path('add-sub-category/<int:catId>/', views.addSubCategory, name='add-sub-cat'),
    path('edit-category/<int:catId>/', views.editCategory, name='edit-category'),
    path('edit-sub-category/<int:subCatId>/', views.editSubCategory, name='edit-sub-cat'),
    path('company-list/', views.CompanyList.as_view(), name='company-list'),
    path('add-company/', views.addCompany, name='add-company'),
    path('edit-company/<int:compId>/', views.editCompany, name='comp-edit-view'),
    path('request-company-list/', views.RequestCompanyList.as_view(), name='request-comp-list'),
    path('approve-comp/<int:compId>/', views.approveDoerCompanyRequest, name='apprrove-company'),
    path('reject-comp/<int:compId>/', views.rejectDoerCompanyRequest, name='reject-company')
]
